"""
migration_execution_agent.py
------------------------------
Agent 10 — Execution Agent  (run-only, no code generation)

Precondition: context.review.status == "APPROVED"

Execution model
---------------
All migration scripts write to the SAME DuckDB file (DUCKDB_PATH env var).
This is intentional — scripts in wave 2 reference silver-layer tables created
by wave 1 scripts (e.g. SELECT ... FROM silver_layer.table1).

To guarantee correct ordering and shared state:

  1. Agent 7b already wrote the orchestrator script run_migration_<run_id>.py
     and recorded its path in context.migration.orchestrator.path.
     This agent does NOT build or write the orchestrator — only runs it.

  2. Each entity migration script (generated by Agent 7a):
       - Opens duckdb.connect(os.environ["DUCKDB_PATH"])
       - Writes its tables to the shared DB file
       - Closes the connection before returning

  3. The orchestrator runs script N only after script N-1 has fully closed
     its connection, so there is never more than one writer at a time and
     every downstream script sees all upstream tables.

  4. This agent runs the orchestrator via subprocess and captures per-step
     logs from its stdout (structured JSON lines).

Reads:  context.migration (artifacts, orchestrator, execution_manifest),
        context.review
Writes: context["execution"]

Output shape:
  {
    "status":             "SUCCESS | FAILED | PARTIAL",
    "rows_processed":     0,
    "failed_tasks":       [...],
    "execution_time":     0,
    "logs":               [...],
    "orchestrator_path":  "outputs/migration/duckdb/run_migration_<id>.py",
    "llm_summary":        { ... },
    "llm_trace":          { ... }
  }

Failure codes: PRECONDITION_FAILED | PARTIAL_EXECUTION | DATA_LOAD_FAILURE
               | UNSUPPORTED_TARGET_DATABASE | LLM_UNAVAILABLE
"""

import os
import sys
import json
import time
import re
import subprocess
from pathlib import Path
from datetime import datetime, timezone

import config
from context import append_audit_event

MAX_RETRIES = 2
RETRY_DELAY = 2
AGENT_NAME  = "ExecutionAgent"
PROMPT_ID   = "migration.execution.v4"


# ── Bedrock helper ─────────────────────────────────────────────────────────────

def _call_bedrock(prompt: str, system: str, label: str = "",
                  max_tokens: int = 2048, temperature: float = 0.0) -> tuple[str, dict]:
    last_error = None
    model_id   = os.getenv("AWS_BEDROCK_MODEL", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
    start_ms   = time.time() * 1000

    for attempt in range(1, MAX_RETRIES + 2):
        try:
            client  = config.get_bedrock_client()
            payload = {
                "anthropic_version": "bedrock-2023-05-31",
                "max_tokens":        max_tokens,
                "system":            system,
                "messages":          [{"role": "user", "content": prompt}],
                "temperature":       temperature,
            }
            response = client.invoke_model(
                modelId=model_id,
                body=json.dumps(payload),
                contentType="application/json",
                accept="application/json",
            )
            body      = json.loads(response["body"].read())
            text      = body["content"][0]["text"]
            latency   = int(time.time() * 1000 - start_ms)
            usage     = body.get("usage", {})
            llm_trace = {
                "model":       model_id,
                "prompt_id":   PROMPT_ID,
                "temperature": temperature,
                "tokens_in":   usage.get("input_tokens", 0),
                "tokens_out":  usage.get("output_tokens", 0),
                "latency_ms":  latency,
            }
            return text, llm_trace
        except Exception as e:
            last_error = e
            wait = RETRY_DELAY * (2 ** (attempt - 1))
            m = re.search(r"retry in\s*([0-9]+(?:\.[0-9]+)?)s", str(e), re.IGNORECASE)
            if m:
                wait = max(wait, int(float(m.group(1))))
            if attempt <= MAX_RETRIES:
                print(f"  ! [{label}] attempt {attempt} failed: {e}. Retrying in {wait}s...")
                time.sleep(wait)

    raise RuntimeError(f"LLM_UNAVAILABLE: {last_error}")


# ── artifact path resolver ─────────────────────────────────────────────────────

def _resolve_artifact_path(rel_path: str) -> Path | None:
    for candidate in [Path(rel_path), Path(config.OUTPUT_DIR).parent / rel_path]:
        if candidate.exists():
            return candidate
    return None


# ── execution log writer ───────────────────────────────────────────────────────

def _write_execution_log(logs: list, run_id: str, target: str) -> str:
    log_dir = Path(config.OUTPUT_DIR) / "migration" / target
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / f"execution_log_{run_id}.json"
    log_path.write_text(json.dumps(logs, indent=2, default=str), encoding="utf-8")
    return str(log_path)


# ── parse orchestrator stdout ──────────────────────────────────────────────────

def _parse_orchestrator_output(stdout: str) -> tuple[list, int, list]:
    """
    Parse structured JSON log lines from orchestrator stdout.
    Returns (step_logs, total_rows, failed_steps).
    """
    step_logs    = []
    total_rows   = 0
    failed_steps = []

    for line in stdout.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
            step_logs.append(entry)
            if entry.get("stage") == "step_end":
                if entry.get("status") == "SUCCESS":
                    total_rows += entry.get("rows_written", 0)
                elif entry.get("status") == "FAILED":
                    failed_steps.append({
                        "step":   entry.get("step"),
                        "entity": entry.get("entity"),
                        "error":  entry.get("error"),
                    })
        except (json.JSONDecodeError, ValueError):
            # Non-JSON line from script (e.g. print statements) — keep as plain log
            step_logs.append({"raw": line})

    return step_logs, total_rows, failed_steps


# ── LLM: post-execution summary ───────────────────────────────────────────────

EXEC_SYSTEM = """You are a database migration execution analyst.

Given an execution log, provide a concise execution summary noting:
- Which entities succeeded and their row counts.
- Which entities failed and the failure reason.
- Whether a rollback is recommended for partial failures.
- Next recommended action (validate / rollback / retry).

Return ONLY valid JSON. No markdown.

Output format:
{
  "executive_summary": "<1-2 sentences>",
  "rollback_recommended": true/false,
  "rollback_entities": ["<EntityName>", ...],
  "next_action": "validate | rollback | retry",
  "notes": ["<note>", ...]
}
"""


# ── main agent entry point ─────────────────────────────────────────────────────

def run_migration_execution_agent(context: dict, verbose: bool = True) -> dict:
    """
    Agent 10 — Execution Agent.
    Precondition: context.review.status == "APPROVED"
    Reads:  context.migration, context.review
    Writes: context["execution"]
    """
    if verbose:
        print("\n" + "=" * 60)
        print("  MIGRATION EXECUTION AGENT  (Agent 10 v4 — run-only)")
        print("=" * 60)

    # ── precondition check ─────────────────────────────────────────────────────
    review_status = context.get("review", {}).get("status")
    if review_status != "APPROVED":
        msg = f"PRECONDITION_FAILED: Review status is '{review_status}', must be APPROVED."
        print(f"  x {msg}")
        context["execution"] = {"status": "FAILED", "error": msg, "llm_trace": {}}
        append_audit_event(context, AGENT_NAME, "precondition_check", "failed", {"error": msg})
        return context

    target = context.get("target_database")
    if target not in ("duckdb", "dynamodb"):
        msg = f"UNSUPPORTED_TARGET_DATABASE: '{target}'"
        print(f"  x {msg}")
        context["execution"] = {"status": "FAILED", "error": msg, "llm_trace": {}}
        append_audit_event(context, AGENT_NAME, "target_validation", "failed", {"error": msg})
        return context

    migration     = context.get("migration", {})
    artifacts     = migration.get("artifacts", [])
    manifest      = migration.get("execution_manifest", {})
    ordered_steps = manifest.get("ordered_steps", [])
    run_id        = manifest.get("run_id", context.get("meta", {}).get("run_id", "unknown"))

    if not ordered_steps:
        msg = "PARTIAL_EXECUTION: No ordered steps in execution manifest."
        print(f"  x {msg}")
        context["execution"] = {"status": "FAILED", "error": msg, "llm_trace": {}}
        append_audit_event(context, AGENT_NAME, "manifest_check", "failed", {"error": msg})
        return context

    # ── validate DUCKDB_PATH is set before doing anything ─────────────────────
    if target == "duckdb" and not os.getenv("DUCKDB_PATH"):
        msg = "CONNECTION_FAILURE: DUCKDB_PATH env var is not set. All scripts share this file."
        print(f"  x {msg}")
        context["execution"] = {"status": "FAILED", "error": msg, "llm_trace": {}}
        append_audit_event(context, AGENT_NAME, "env_check", "failed", {"error": msg})
        return context

    if verbose:
        print(f"  Target            : {target}")
        print(f"  Steps to run      : {len(ordered_steps)}")
        print(f"  Python interpreter: {sys.executable}")
        if target == "duckdb":
            print(f"  DUCKDB_PATH       : {os.getenv('DUCKDB_PATH')}")
            print(f"  SOURCE_DATA_DIR   : {os.getenv('SOURCE_DATA_DIR', 'not set')}")

    # ── resolve orchestrator written by Agent 7b ───────────────────────────────
    orchestrator_info = migration.get("orchestrator", {})
    orchestrator_rel  = orchestrator_info.get("path", "")
    if not orchestrator_rel:
        msg = "PARTIAL_EXECUTION: context.migration.orchestrator.path is missing. Run Agent 7b first."
        print(f"  x {msg}")
        context["execution"] = {"status": "FAILED", "error": msg, "llm_trace": {}}
        append_audit_event(context, AGENT_NAME, "orchestrator_check", "failed", {"error": msg})
        return context

    orchestrator_path = _resolve_artifact_path(orchestrator_rel)
    if orchestrator_path is None:
        msg = f"PARTIAL_EXECUTION: Orchestrator file not found at {orchestrator_rel}. Run Agent 7b first."
        print(f"  x {msg}")
        context["execution"] = {"status": "FAILED", "error": msg, "llm_trace": {}}
        append_audit_event(context, AGENT_NAME, "orchestrator_check", "failed", {"error": msg})
        return context

    if verbose:
        print(f"  Orchestrator      : {orchestrator_path}")
        print(f"  Running orchestrator...")

    # ── run orchestrator ───────────────────────────────────────────────────────
    t_start = time.time()
    timeout = int(os.getenv("MIGRATION_TOTAL_TIMEOUT", "3600"))  # 1hr default for full run

    try:
        result = subprocess.run(
            [sys.executable, str(orchestrator_path)],
            capture_output=True,
            text=True,
            env=os.environ.copy(),
            timeout=timeout,
        )
        stdout = result.stdout
        stderr = result.stderr.strip()

    except subprocess.TimeoutExpired:
        msg = f"DATA_LOAD_FAILURE: Orchestrator timed out after {timeout}s"
        print(f"  x {msg}")
        context["execution"] = {
            "status": "FAILED", "error": msg,
            "orchestrator_path": str(orchestrator_path), "llm_trace": {},
        }
        append_audit_event(context, AGENT_NAME, "orchestrator_run", "failed", {"error": msg})
        return context

    except Exception as e:
        msg = f"DATA_LOAD_FAILURE: Failed to run orchestrator — {e}"
        print(f"  x {msg}")
        context["execution"] = {
            "status": "FAILED", "error": msg,
            "orchestrator_path": str(orchestrator_path), "llm_trace": {},
        }
        append_audit_event(context, AGENT_NAME, "orchestrator_run", "failed", {"error": msg})
        return context

    exec_time = round(time.time() - t_start, 2)

    # ── parse orchestrator output ──────────────────────────────────────────────
    step_logs, total_rows, failed_steps = _parse_orchestrator_output(stdout)

    if result.returncode == 0:
        exec_status = "SUCCESS"
    elif failed_steps and len(failed_steps) < len(ordered_steps):
        exec_status = "PARTIAL"
    else:
        exec_status = "FAILED"

    # Surface stderr if orchestrator itself crashed (not a step failure)
    if result.returncode != 0 and not failed_steps and stderr:
        step_logs.append({"stage": "orchestrator_crash", "stderr": stderr})

    # ── write execution log ────────────────────────────────────────────────────
    log_path = _write_execution_log(step_logs, run_id, target)

    # ── LLM post-execution summary ─────────────────────────────────────────────
    llm_trace    = {}
    exec_summary = {}
    try:
        prompt = f"""Summarise this migration execution log.
TARGET: {target}
LOGS:
{json.dumps(step_logs, indent=2)}
"""
        raw, llm_trace = _call_bedrock(prompt, EXEC_SYSTEM, label=AGENT_NAME)
        exec_summary   = json.loads(raw.strip().lstrip("```json").rstrip("```").strip())
    except Exception as e:
        if verbose:
            print(f"  ! LLM summary failed (non-blocking): {e}")

    context["execution"] = {
        "status":             exec_status,
        "rows_processed":     total_rows,
        "failed_tasks":       failed_steps,
        "execution_time":     exec_time,
        "logs":               step_logs,
        "log_file":           log_path,
        "orchestrator_path":  str(orchestrator_path),
        "llm_summary":        exec_summary,
        "llm_trace":          llm_trace,
    }

    append_audit_event(context, AGENT_NAME, "execute_migration", "completed", {
        "status":             exec_status,
        "rows_processed":     total_rows,
        "failed_count":       len(failed_steps),
        "execution_time":     exec_time,
        "orchestrator_path":  str(orchestrator_path),
    })

    if verbose:
        print("\n" + "=" * 60)
        print("  MIGRATION EXECUTION COMPLETE")
        print("=" * 60)
        print(f"  Status            : {exec_status}")
        print(f"  Rows Processed    : {total_rows}")
        print(f"  Failed Tasks      : {len(failed_steps)}")
        print(f"  Execution Time    : {exec_time}s")
        print(f"  Orchestrator      : {orchestrator_path}")
        print(f"  Log File          : {log_path}")
        print("=" * 60)

    return context